### ISSUE TITLE
10.15升级

### ISSUE THREAD

**Issue by dukeduffff** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#1]
目前从10.14.6可以从系统升级10.15啦，需要升级clover和驱动即可

**Comment by Swung0x48** [comment]
似乎我这边升级10.15有点问题。你的10.15如果可用，能不能提交一个PR？

**Comment by dukeduffff** [comment]
我擦，我从mojave升级上来，用了几天，感觉完美了，突然不能启动了，开机直接重启，应该是显卡驱动的问题

**Comment by Swung0x48** [comment]
Nothing useful.
