### ISSUE TITLE
OpenCore version

### ISSUE THREAD

**Issue by EfraimLA** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#10]
Is it possible to have an OC version? Clover is getting deprecated, some way to parse it?

**Comment by Swung0x48** [comment]
It is on the way. Stay tuned.

**Comment by Swung0x48** [comment]
OpenCore version now available at 40a519a15a1383be4a96e88f9a0e7589ead54785.
Check `Catalina-OpenCore` branch.
