### ISSUE TITLE
How to remove key mappings?

### ISSUE THREAD

**Issue by JonHolman** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#11]
First off, thank you very much for making this available.  It helped me resolve many driver/kext issues I was having.  I do have a question, hope you don't mind.  Where are the key mappings being set?  I would like to remove them.  I can go System Preferences > Keyboard to reset them, but they often come back.  Thank you for your time.

**Comment by Swung0x48** [comment]
You may remove `SSDT-BKeyBRT6-dell-PS2K.aml` and `SSDT-FnInsert_BTNV-dell.aml` from `EFI/CLOVER/ACPI/patched`

**Comment by JonHolman** [comment]
Thanks!

**Comment by JonHolman** [comment]
FYI, it looks like `SSDT-FnInsert_BTNV-dell.aml` is involved in allowing the screen to turn off when closed, so I put it back.
