### ISSUE TITLE
No disk detected on install screen ( Latitude 7490 i5 8250U )

### ISSUE THREAD

**Issue by huskytech9** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#16]
Hi
I am not able to see any disk after boot. I have all clicked on view all still only USB. Please see screenshot below

![B9C80EC2-64D4-4E58-8927-7E1E2735B7FF](https://user-images.githubusercontent.com/63915924/86547276-744af580-bf06-11ea-9e0a-90dbb337fc63.jpeg)

**Comment by Swung0x48** [comment]
Which SSD is there in your system?
Note Samsung PM981, some Hynix SSDs are not supported by macOS natively.

**Comment by huskytech9** [comment]
Hi It is LITEON SATA SSD
![42BAB013-6E1E-471A-89C1-B5688CEE6EE9](https://user-images.githubusercontent.com/63915924/86548580-ee7d7900-bf0a-11ea-9ef3-2e79f522b296.jpeg)

**Comment by huskytech9** [comment]
Any idea what I am doing wrong

**Comment by Swung0x48** [comment]
LiteON/PLEXTOR NVMe SSDs are not natively supported by macOS. There are several patches out there to work around this. Or you need to swap the drive for something that is natively supported, such as WD SN series or Samsung ones other than PM981/970 EVO|Pro Plus(Non-plus versions are good to go）.

**Comment by huskytech9** [comment]
Thats sad, I have to stay with this SSD. Thanks for your help. I have no idea about patch

**Comment by Swung0x48** [comment]
You can check the patch here. https://github.com/RehabMan/patch-nvme
No support for these patches in this repo. Will close this issue by now.
