### ISSUE TITLE
no files

### ISSUE THREAD

**Issue by aristeidk2** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#18]
the code download is empty.
only a help file and nothing else

**Comment by Swung0x48** [comment]
Read the README CAREFULLY.

**Comment by aristeidk2** [comment]
I was read carefully. No efi folder no files. Haw can i hackintosh the latitude 7390 without files?

**Comment by Swung0x48** [comment]
Make sure you have read EVERY SINGLE WORD in the README. Issue closed. Happy Hackintosh.
