### ISSUE TITLE
Dell Latitude 7390 Catalina

### ISSUE THREAD

**Issue by agapiospanos** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#2]
Hello. Thank you for providing us the EFI configuration! I really appreciate it.

I have a Latitude 7390 with an i5 8250u, 8GB RAM and a Toshiba KXG60ZNV256G 256GB NVMe. I tried your 10.15 files to boot into Catalina but without success. I managed to boot into the installation but without keyboard and touchpad. I had to use an external usb keyboard and the touchscreen. I managed to format the drive to APFS and GUID and then started the installation. The installation finished and the machine restarts. After the restart it continues the installation in the apple logo where after the completion it restarts again. After the last restart I cannot boot into the OS to continue the configuration. I get a kernel panic no matter what I try. I used every possible configuration and I still cannot make it. I get a lot of errors about the ACPI.

I have configured my BIOS using this tutorial https://osxlatitude.com/forums/topic/11477-7490-bios-settings/

The errors I get are almost identical to those shown in the image at this reddit
https://www.reddit.com/r/hackintosh/comments/e6acdi/question_im_new_to_hackintosh_and_am_unsure_on/

Any ideas on how to proceed. I got too close and I 've been struggling for about a week.

Thank you very much,
Agapios

**Comment by Swung0x48** [comment]
I don't know for sure, but I suspect there's something wrong with the NVMe drive.
Do you have any USB external drives lying around? Try installing on them to see if it is the case.
BTW, touchpad not working under installation guide is expected.

**Comment by agapiospanos** [comment]
Thank you very much for the quick response. 

I managed to solve the problem by adding an acpi patch. I have already added an NVMe kext to be able to boot using the NVMe drive. Now I am struggling with the intel GPU as I am facing the quite common problem with the 7mb VRAM and no HW acceleration. I am sure I will find a solution.

Thank you again!
Cheers!

**Comment by Swung0x48** [comment]
So, may you tell me which acpi patch did you apply? 
For the GPU problem, you may use Hackintool to generate a Framebuffer.

**Comment by agapiospanos** [comment]
Thank you for the hint. I saw that there were plenty of posts referring to the hackingtool but I could not figure out how to properly produce the correct patch. I used many ids like 0x59160000, 0x19160000 and 0x3E9B0000 but none of them worked. 

Did you also apply a patch using the Hackingtool? If so, what settings did you use? Do you have the QE/CI working and metal working?

I managed to have the QE/CI working according to Intel FB-Patcher v 1.6.8 but in the metal field, I got a No. And also the VRAM is only 7mb. After this, I am sure that I need to patch the Frame Buffer but I could not find the correct settings...

As for the ACPI patch that I applied to be able to boot was 
FInd HEX:        A00A9353 54415301
Replace HEX:  A00A910A FF0BFFFF

After adding this patch I got rid of the error that I posted in the first post.

Thank you very much for your time!

**Comment by agapiospanos** [comment]
And finally SUCCESS!!!! I used from your config the part about devices. Everything is working now. I have sound, brightness control and both QE/CI and Metal On. So the laptop is perfoming at its best. The only issue now is that the blue color in the display is displayed a bit off. It is more purple than it is supposed to be. Other colors seem to be rendered correctly. But blue is not blue... Did you notice that issue on your machine? It is pretty obvious if I look at the App Store, Safari, Finder, Facebook logo that seem very purple instead of blue.

----- EDIT:
Found the fix for it. It seems that the OS just detected the wrong colour profile. The solution is to just open the system preferences -> display -> colour (tab) and pick the last profile. sRGB IEC61966-2.1. The colours will be back to normal then.

**Comment by Swung0x48** [comment]
Check for your color profile. It should be sRGB IEC61966-2.1.

**Comment by agapiospanos** [comment]
Yes, indeed that was the problem. Thank you very much for your kind help! Cheers!

**Comment by Swung0x48** [comment]
Fine. Enjoy your Hac!

**Comment by aristeidk2** [comment]
I have the same laptop (latitude 7390 2 in 1) i cannot found the efi folder.
