### ISSUE TITLE
No trackpad at all

### ISSUE THREAD

**Issue by Euentropic** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#20]
Hi, Swung0x48. I tried Opencore boot in my Dell Latitude 7490 with 16GB, NVME 1TB and intel core I5. Everything is great. (The sound at first is fantastic) and I got every function working except trackpad. Neither trackpad nor trackpad buttons work at all. Tried with Clover and I got the same behaviour. Maybe your are working on it and planning to fix it in the future. Now I'm back to Opencore (it is a lot faster!) and working with a usb mouse. Facebook and iMessage do not work either, but that's not a big deal. Thank you for your work and please, let me know if you find a solution for trackpad surface and buttons. Maybe even getting to work as a basic mouse would be fine. Thanks again.
Euentropic.

**Comment by Euentropic** [comment]
Sorry, It's repeated.

**Comment by Swung0x48** [comment]
It should work. Try rebooting/cleaning kext cache?
Dunno duplicated to which, leave a link if you still think so.
