### ISSUE TITLE
7490 OpenCore 0.63

### ISSUE THREAD

**Issue by punjabigator** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#24]
I hope all is well with you. First of all thank you for your efforts and sharing the EFI. First question, how can I download the OpenCore EFI from your repo? Please guide. Also would you able to update it to 0.63? Look forward to hearing from you. Regards

**Comment by Swung0x48** [comment]
First of all, thanks for your appreciation. You may switch to branch opencore-catalina to download the latest version. Because I have already sold the laptop, I cannot get this repo up to date. There's no plan of upgrading, though you way do it yourself if you would like to.
