### ISSUE TITLE
Issue about config.plit and AppleIntelLpssI2CController error

### ISSUE THREAD

**Issue by persistz** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#25]
Thanks for the EFI.
As mentioned in ReadMe, you have already sold this laptop, 
I would be very grateful if you can provide any information or material.

I used the EFI under OC branch, then Catalina hackintosh was successfully installed.
But after I run 'Migration Assistant' and robot, an AppleIntelLpssI2CController error occurred.

For these S\L\E kexts, in the era of Clover, I could use CoolStar's patch to fix them. 
You also used this part of the code in Clover’s branch, seems like:

```
<dict>
<key>Comment</key>
<string>Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar</string>
<key>Name</key>
<string>com.apple.driver.AppleIntelLpssI2C</string>
<key>Find</key>
<data>SU9LaXQ=</data>
<key>Replace</key>
<data>SU9LaXM=</data>
<key>InfoPlistPatch</key>
<true/>
</dict>
```

But in the OC's 'Kernel => Patch' parts, I did not find any relevant content. 
Is it because this part of the patch no longer needs to be added? OR just as I did not find these patches?
OR any ideas about the panic caused by 'AppleIntelLpssI2CController'?

![image](https://user-images.githubusercontent.com/12887616/101464988-56346600-397a-11eb-8b4d-8b714a51f099.png)

**Comment by Swung0x48** [comment]
Try to update the BIOS to EXACTLY 1.13.1 (If you are using 7490). I might put some dirty hacks in SSDT-TPDX and it maybe BIOS related.
That patch, from my experience, is not necessary. It cannot be loaded by OpenCore either. So I just don't bother put it in the config.

**Comment by persistz** [comment]
Thanks for your reply, I have updated the BIOS but the problem still comes.
I will learn SSDT-TPDX hacks, try potential solutions.
