### ISSUE TITLE
Wifi not working

### ISSUE THREAD

**Issue by somabencsik** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#26]
Hello, in the readme.md you wrote everything is working, but for me the wifi is not working and it wouldn't be a problem, but when I connect a wifi stick, the system is now responding anything to it. I have the 7490 of Latitude.

Thanks in advance!

**Comment by somabencsik** [comment]
I could solve the problem, I did not saw that you used another wifi card. I found some kexts which solved my problem. I would link the video which showed me the right way, but I don't know if I am allowed to, so I just close this issue.

**Comment by Swung0x48** [comment]
USB wifi sticks are not related to this repo. But for these Realtek based USB wifi, a simple pkg will do the trick.
