### ISSUE TITLE
10.15: macOS Catalina 10.15.3 Dell Latitude 7490

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#4]
I get to the install screen and then it seems to be freezing?
Cant move my mouse with the touchpad or a connected mouse?

Any ideas?

**Comment by Swung0x48** [comment]
Try to add `-igfxvesa` boot arg for installation, which will temporarily disable the GPU acceleration

**Comment by Swung0x48** [comment]
No further reply. Will close this issue.
