### ISSUE TITLE
HDMI display with purple mask

### ISSUE THREAD

**Issue by dancingCode007** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#5]
Issue as the title.

**Comment by Swung0x48** [comment]
Some certain displays will encounter this. This is not the issue with the EFI. 
Search for "Force HDMI RGB output" tutorial.
Or change your display's color profile to YUV in display's OSD. (AFAIK, some of the dell ones could do that).

**Comment by dancingCode007** [comment]
I have found that the reason is default clover configuration for HDMI output as DP. It's OK after migrating  DP channel to HDMI.
Thanks.
