### ISSUE TITLE
Audio for Dell Latitude 7390 2-in-1

### ISSUE THREAD

**Issue by superguyadi** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#6]
Audio didn't work for me(ALC 256)
Used VoodooHDA.kext

Problem:
Microphone not working
Updating  OSX to 10.15.4 causes Kernel Panics

After Sleep, the machine cannot wake up, needs a reboot

Thanks to @Swung0x48 for making this possible, I am very happy with this Hackintosh.

EDIT:
Microphone worked on layout-16, Audio is good.

**Comment by Swung0x48** [comment]
This repo is not intended to support 2in1 models btw.
But some insights could be given.
Try Fn+Insert (should be a moon icon on the keyboard) when the system is running and wait for about 30s. Does it reboot or sleep properly?
For audio, try to make sure layout id 11 is injected.
Thanks for your appreciation!

**Comment by superguyadi** [comment]
@Swung0x48 , Microphone worked on layout-16, Audio is good.
Keep UP the Good work.
The moon Icon on is on "END" key on 7390 2-in-1, it works.
After 30 seconds the fans stops and it goes to sleep. I will test more and tell.
Alt+Ctrl+Power is reboot, right?

Fan spins aggressively all the time, I have recently applied new thermal paste and there is no problem when using Windows. "Macs Fan control" app can't find any Fan. Fan is not on Full speed but it is near full speed. The system also runs a little hot. The battery drain can be tweaked? Drain is not too bad but can be better. I get 10+ hours on this laptop on full charge with light use(a little web browsing and movies mostly)

Also, I am using Laptop in a well-ventilated place.

1. Android USB Tethering works great! I don't have a Broadcom WLAN yet.
2. SD card reader works great.
3. Touchscreen works great.(No multi-touch support though)
4. Webcam and in-buil microphone works.
5. Headphone Jack works

Your repo is 100% working on 2-in-1 model.
without any changes. I had to update clover to 5102, rest kexts, patched acpi, Drivers and config.plist is taken from your repo.

**Comment by superguyadi** [comment]
This repo technically supports 2-in-1 better, ThunderBolt is detected(not tested)
This laptop has:
Intel i7 8650u vPro
16 GB Dual Channel 2133 MHz RAM

Does not have:
Smart-card reader
FingerPrint scanner
TrackPoint

I am very much happy that you are working on it. Please maintain it if you can.

I suggest:
1. Better Themal(fan) and power management
2. Update to support latest 10.15.4 OSX
3. TrackPad Buttons
Extras:
1. Multi-touch support for gestures(Pinch, Scroll etc)
2. The utilisation of Infrared Camera(for third party face recognition app like https://github.com/boltgolt/howdy )

**Comment by superguyadi** [comment]
I want to try using OpenCore version.
I am on Clover+10.15.3

Should I make a fresh install? 
Or should I replace the Files in EFI partition of the existing 10.15.3 and then update to 10.15.5?

I am having 7390 2-in-1, SD Card reader works perfectly in 10.15.3+Clover but you have disabled it in OpenCore+10.15.5.
How can I enable it for my laptop?

**Comment by superguyadi** [comment]
I want to buy a WLAN Card.
Can you please tell me whether DW1560 works perfectly? Continuity, Handoff, Hotspot, Apple Watch unlock etc?
DW1560 is cheaper than BCM94360NG which has out of the box support for everything.

**Comment by Swung0x48** [comment]
> I want to try using OpenCore version.
> I am on Clover+10.15.3
> 
> Should I make a fresh install?
> Or should I replace the Files in EFI partition of the existing 10.15.3 and then update to 10.15.5?
> 
> I am having 7390 2-in-1, SD Card reader works perfectly in 10.15.3+Clover but you have disabled it in OpenCore+10.15.5.
> How can I enable it for my laptop?

The OpenCore branch is merged from #12 and I haven't personally tested it out yet. The SD card reader thingy is just a kext I believe. Just throw it in `OC/Kexts` and it should work.

**Comment by Swung0x48** [comment]
> I want to buy a WLAN Card.
> Can you please tell me whether DW1560 works perfectly? Continuity, Handoff, Hotspot, Apple Watch unlock etc?
> DW1560 is cheaper than BCM94360NG which has out of the box support for everything.

I personally don't have an Apple Watch so that I cannot test out the Watch unlock feature. Other than that DW1560 should work fine for the features you mentioned. If configured correctly(I believe my Clover version is fully-tuned for that).

**Comment by muttonhead411** [comment]
> Should I make a fresh install?
> Or should I replace the Files in EFI partition of the existing 10.15.3 and then update to 10.15.5?

Hi there, I strongly suggest a fresh install, and restore with time machine or target disk mode. OpenCore guide has a process to migrate from existing clover setups, but its not encouraged as they function very differently in NVRAM. A clean setup will give you the highest chance of success when you move to opencore.

**Comment by superguyadi** [comment]
@muttonhead411 
I just clean installed 10.15.5 with opencore.
-Audio is not working (no output and no input device)
-USB tethering used to work on 10.15.3, it's not working anymore.

Edit

These all features used to work in clover+10.15.3

I'm using 7390 2-in-1

Please tell how to change Audio layout ID in the OpenCore version to bring back audio.
Thanks!

Edit-2

-After sleep, my password stopped working. I tried multiple times. The password is simple '1234' can't be forgotten. Weird issue, never happened on old build.

Edit-3
Audio is working on 7390 2-in-1(Codec=ALC3253) Layouts possible 28,30(best),33.
Steps followed:
-Add "alcid=30"string < boot-args <add<nrvram in config.plist file.

Optional steps but I recommend:
-Delete SSDT-ALC256.aml from ACPI folder
-Removed SSDT ALC256 loading code from Config.plist

**Comment by superguyadi** [comment]
Dell 7390 2-in-1 does not have Realtek ALC256 audio chip.

It comes with:
Audio Adapter:                            Intel Kaby Lake-U/Y PCH - High Definition Audio Controller
Audio Controller Hardware ID:    PCI\VEN_8086&DEV_9D71&SUBSYS_08231028&REV_21

Please tell me how to enable audio-layout-11 and should I remove and replace the SSDT:
EFI/OC/ACPI/SSDT-ALC256.aml ?

I am completely noob, please tell if it will require any NVRam Reset or kextcache rebuilding.

**Comment by Swung0x48** [comment]
Seems fixed in #30.

**Comment by Swung0x48** [comment]
Please do not use VoodooHDA.
Audio seems fixed on 7490@OpenCore version with layout id 17.
This repo is not intended to support 2-in-1 models.
