### ISSUE TITLE
Physical buttons

### ISSUE THREAD

**Issue by GordonWen** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#7]
I didn't have the TrackPoint(BluePoint), But without TrackKeys is unused to op.....
How about to fix the Physical buttons.... ?

**Comment by Swung0x48** [comment]
It’s beyond my ability. VoodooI2C.kext simulates the trackpad as an Apple Trackpad 2. As you can see, it does not receive pressure only without coordination, for it does not has physical buttons on it.
