### ISSUE TITLE
Trackpad & BIOS Config - Latitude 7490

### ISSUE THREAD

**Issue by EfraimLA** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#8]
I did try with Catalina 10.15.4 and trackpad doesn't work but doesn't seem to be a problem with macOS version, also what are the full BIOS settings?

**Comment by Swung0x48** [comment]
try running init.command to purge kext cache in order to fix the trackpad. BIOS settings seems to be not related. If you find that a specific bios setting may have something to do with it, comment below.

**Comment by EfraimLA** [comment]
K where do i execute that script? From macOS recovery window?

**Comment by EfraimLA** [comment]
I got this and still doesn't work

![20200403_121904](https://user-images.githubusercontent.com/46459026/78392477-85056b80-75a5-11ea-8867-8c1d62f36ff1.jpg)

**Comment by Swung0x48** [comment]
In the system. After you boot into desktop

**Comment by EfraimLA** [comment]
Got stuck in apple logo

Steps:

1. Install from USB (well done)
2. Reboot to macOS installer from SSD, appears logo with time remaining (well done)
3. Reboot to macOS from SSD (stuck at logo with progress bar aprox. 20%)  

Here are verbose logs:
![20200403_164131](https://user-images.githubusercontent.com/46459026/78410586-066ef500-75ca-11ea-9726-2fcf5621c884.jpg)

**Comment by EfraimLA** [comment]
Known reason?

**Comment by EfraimLA** [comment]
Someee? I need help with this ):

**Comment by muttonhead411** [comment]
Hi @EfraimLA - Trackpad does not work in installer, so use an external mouse first.

Once you successfully install Catalina, then trackpad should work. 

Also, not sure if you're on OpenCore or Clover, but you do not need GPIO SSDT. But first try the above.

**Comment by EfraimLA** [comment]
Yes i did install without trackpad but when i'm booting it appears me (what's in the picture)

**Comment by muttonhead411** [comment]
I think you should reinstall fresh. If you can boot into installer USB, you should install fine. I can't see the problem from your screenshot

**Comment by EfraimLA** [comment]
Some special BIOS Configurations are required? I'll try again

**Comment by EfraimLA** [comment]
Did try to make a fresh installation but stuck at rebooting

**Comment by EfraimLA** [comment]
Stuck here, some idea?

![20200504_214630](https://user-images.githubusercontent.com/46459026/81031129-da58c500-8e50-11ea-8691-c4b4378b277d.jpg)

**Comment by EfraimLA** [comment]
![20200504_215442](https://user-images.githubusercontent.com/46459026/81031513-17718700-8e52-11ea-8bf4-2c096dde789f.jpg)

**Comment by EfraimLA** [comment]
I did notice there's an error when I'm installing it gets on panic

EDIT: Keeps me in panic, installing, after install, etc. Only cannot boot):

**Comment by Swung0x48** [comment]
Try the OpenCore one for a clean approach.
