### ISSUE TITLE
Headphone audio & SD card reader

### ISSUE THREAD

**Issue by nmalasevic** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#9]
Hi, I have found a way to enable audio in headphones, though is not perfect yet (amplifier gain is too high so there is some background noise) and I wanted to share it with you. To get it working just switch ALC to layout id 21 by adding it to boot arguments: **alcid=21**. Other layouts have better headphone support but then speakers don't work properly, so 21 is the best compromise.

As for SD card reader, you can enable it by adding kext found here:
https://github.com/cholonam/Sinetek-rtsx/releases

Cheers.

**Comment by muttonhead411** [comment]
@nemanjamalasevic @Swung0x48 I managed to get headphone jack working with a fix described here:
https://www.elitemacx86.com/threads/fix-audio-distortion-when-using-headphones-on-laptops.185/

Hope it helps all of us owners using 7490, and other ALC256 owners.

**Comment by nmalasevic** [comment]
UPDATE: Headphones are completely fixed!
Just update [AppleALC](https://github.com/acidanthera/AppleALC) kext to 1.4.9 and change layout-id in boot parameters to 17: **alcid=17**. Headphones should work perfectly fine now, without any background noise! It's recommended to update [Lilu](https://github.com/acidanthera/Lilu) and [Weg](https://github.com/acidanthera/WhateverGreen) to latest versions as well.

**Comment by muttonhead411** [comment]
@nemanjamalasevic - Did you need codec commander for this fix?

**Comment by muttonhead411** [comment]
I can confirm @nemanjamalasevic finding, all is working well with updated kext and layout-id = 17. I have injected via Device Properties successfully as well.

**Comment by Swung0x48** [comment]
> I can confirm @nemanjamalasevic finding, all is working well with updated kext and layout-id = 17. I have injected via Device Properties successfully as well.

Would you like to create a pull request?

**Comment by TheToto318** [comment]
Hey,
SD card fix is working for me but the new ALC kext bread the hotkeys and the speaker audio for me, changed alcid to 17 but same thing.

**Comment by Swung0x48** [comment]
SD card reader fixed in the OpenCore version.
Audio/Headphone jack: ref to #6.
Will close this issue.
